optim:
  name: adamw
  lr: 1e-4
  kwargs: {} # TODO add this in default config when created

loss:
  name: ce-loss
  kwargs: {}

scheduler:
  name: cosine
  kwargs:
    max_lr: ${optim.lr}
    total_steps: 1000

model: 
  name: simple-gcn
  kwargs:
    num_features: 7 
    hidden_dim: 64
    num_classes: 2

callbacks:
  use_early_stopping: true
  early_stopping_epochs: 5


num_epochs: 100
batch_size: 64