optim:
  name: adamw
  lr: 1e-4
loss:
  name: ce-loss
scheduler:
  name: cosine
  kwargs:
    max_lr: ${optim.lr}
    total_steps: 800
model: 
  name: simple-gcn
  kwargs:
    num_features: 140 
    hidden_dim: 128
    num_classes: 6
callbacks:
  use_early_stopping: true
  patience: 5
data:
  root: data/braak_xy_expression_by_celltype_donor_lognorm_zscore
  k: 30
num_epochs: 256
batch_size: 16
device: 'cuda:0'
run_name: run_1