optim:
  name: adamw
  lr: 1e-4

loss:
  name: ce-loss

scheduler:
  name: cosine
  kwargs:
    max_lr: ${optim.lr}
    total_steps: 10000

model: 
  name: simple-gcn
  kwargs:
    num_features: 140 
    hidden_dim: 128
    num_classes: 6

callbacks:
  use_early_stopping: true
  early_stopping_epochs: 5

data:
  root: data/braak_xy_expression_by_celltype_donor_lognorm_zscore
  k: 20
num_epochs: 500
batch_size: 20
# device: 'cpu'