optim:
  name: adamw
  lr: 1e-4
  kwargs: {} # TODO add this in default config when created

loss:
  name: ce-loss
  kwargs: {}

scheduler: null

model: 
  name: simple-gcn
  print_summary: true
  num_models_to_save: 5
  kwargs:
    num_features: 140 
    hidden_dim: 64
    num_classes: 6

callbacks:
  use_early_stopping: true
  patience: 5

data:
  root: null
  k: 10
num_epochs: 100
batch_size: 4
device: null
run_name: run_1
work_dir: work_dir